name: Déploiement FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload vers le serveur
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Déployer par FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: sites/planning.pharmaciedumarais.net/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            *.bak
            debug_*.php
